# Description: Docker compose file for bind9
services:
  bind9:
    build: 
      dockerfile: Dockerfile
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    restart: unless-stopped
    volumes:
      - ./bind/named.conf.options:/etc/bind/named.conf.options
      - ./bind/named.conf.local:/etc/bind/named.conf.local
      - ./bind/zones:/etc/bind/zones
      - ./cache:/var/cache/bind